export const WORDLE_INTERVAL_MS = 6 * 60 * 60 * 1000;
export const WORDLE_START_MS = 1641978000000; // 2022/01/12 12:00 +03:00
export const WORDLE_STORAGE_KEY = "@CurrentWordle";
export const WORDLE_HISTORY_STORAGE_KEY = "@WordleHistory";
export const MAX_GUESS_COUNT = 6;
export const WORDLE_LENGTH = 5;
export const WORDLE_SHARE_MISPLACED = "🟨";
export const WORDLE_SHARE_CORRECT = "🟩";
export const WORDLE_SHARE_WRONG = "⬛";
